# This workflow will scrap GitHub trending projects daily.

name: Daily Github Trending

on:
  schedule:
  - cron: "*/15 * * * *" 
#   push: 
#     branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Python 11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scraper
      run: |
        python scraper.py

    # Runs a set of commands using the runners shell
    - name: Push to origin master
      run: |
        echo start push
        git config --global user.name "renshenglu"
        git config --global user.email "renshenglu1010@gmail.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
        
